name: Doc build

on:
  push:
    branches: [ master , develop]
  pull_request:
    branches: [ master , develop]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Node v11.0
      uses: actions/setup-node
      with:
        node-version: 11.0
    - name: Install dependencies
      run: |
        npm install
    - name: Test build
      run: |
        npm run build
